<button class="btn btn-success" onclick="location.href='/admin/locais-de-trabalho/save'">Novo local de trabalho</button>

<table class="table">
    <thead>
    <tr>
        <td>Id</td><td>Nome</td>
    </tr>
    </thead>
    <tbody>
    <?php foreach($locais_de_trabalho as $local_de_trabalho) {
        ?>
        <tr>
            <td>
                <?php echo $local_de_trabalho->getId(); ?>
            </td>
            <td>
                <?php echo $local_de_trabalho->getNome(); ?>
            </td>
            <td>
                <a href="/admin/locais-de-trabalho/save/id/<?php echo $local_de_trabalho->getId(); ?>">Editar</a>
            </td>
            <td>
                <a href="/admin/locais-de-trabalho/delete/id/<?php echo $local_de_trabalho->getId(); ?>">Excluir</a>
            </td>
        </tr>
    <?php }
    ?>
    </tbody>

</table>
