<button class="btn btn-success" onclick="location.href='/admin/tipos-de-telefone/save'">Novo tipo de telefone</button>

<table class="table">
    <thead>
    <tr>
        <td>Id</td><td>Descrição</td>
    </tr>
    </thead>
    <tbody>
    <?php foreach($tipos_de_telefones as $tipo_de_telefone) {
        ?>
        <tr>
            <td>
                <?php echo $tipo_de_telefone->getId(); ?>
            </td>
            <td>
                <?php echo $tipo_de_telefone->getDescricao(); ?>
            </td>
            <td>
                <a href="/admin/tipos-de-telefone/save/id/<?php echo $tipo_de_telefone->getId(); ?>">Editar</a>
            </td>
            <td>
                <a href="/admin/tipos-de-telefone/delete/id/<?php echo $tipo_de_telefone->getId(); ?>">Excluir</a>
            </td>
        </tr>
    <?php }
    ?>
    </tbody>

</table>
